AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - node_modules/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/initializers/simple_form_bootstrap.rb
    - config/initializers/simple_form.rb

Metrics/BlockLength:
  Exclude:
    - config/initializers/devise.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
