AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - config/initializers/devise.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*
Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
